[tool.poetry]
name = "da-parttime"
version = "0.1.0"
description = ""
authors = ["Rai Rintarou <ikkmno123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.45.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
